In [102]:
import numpy as np

In [103]:
my_lst=[1,2,3,4,5,6]

In [104]:
arr=np.array(my_lst)
arr

array([1, 2, 3, 4, 5, 6])

In [105]:
print(type(arr))
print(len(arr))
print(arr.ndim)
print(print(arr.shape))

<class 'numpy.ndarray'>
6
1
(6,)
None


In [106]:
arr = arr.reshape(2,3)

In [107]:
arr.ndim

2

In [108]:
arr=arr.reshape(3,-1) #-1 mean other dimension calculated by nu,kpy automatically
arr.ndim

2

In [109]:
my_lst2=[1,2,3,4,5]
my_lst3=[2,3,4,5,6]
my_lst4=[9,7,6,8,9]

In [110]:
null_arr=np.array([my_lst2,my_lst3,my_lst4])

In [111]:
null_arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [112]:
null_arr.shape

(3, 5)

In [113]:
null_arr=null_arr.reshape(1,1,3,5)

In [114]:
null_arr.ndim

4

In [115]:
r=range(24)

In [116]:
print(r)

range(0, 24)


In [117]:
a=np.arange(24)
a.ndim

1

In [118]:
a=a.reshape(6,4,1)

In [119]:
a

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23]]])

In [120]:
x=np.array([[1,2],[3,4]],dtype=float)
y=np.array([[5,6],[7,8]])

In [121]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

In [122]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [123]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [124]:
a=np.subtract(x,y)

In [125]:
x=np.array([[1,-2],[3,4]])

In [126]:
np.positive(x)

array([[ 1, -2],
       [ 3,  4]])

In [130]:
np.logaddexp2(x,0)

array([[1.5849625 , 0.32192809],
       [3.169925  , 4.08746284]])

In [128]:
x

array([[ 1, -2],
       [ 3,  4]])

In [129]:
np.power(x,2)

array([[ 1,  4],
       [ 9, 16]])

In [78]:
np.remainder(y,2)

array([[1, 0],
       [1, 0]])

In [92]:
x

array([[ 1, -2],
       [ 3,  4]])

In [93]:
np.sum(x,axis=0)

array([4, 2])

In [94]:
np.sum(x,axis=1)

array([-1,  7])

In [95]:
import os

In [99]:

os.chdir(r"C:\Users\Lenovo\anaconda3\Lib\site-packages\pandas")

In [100]:
pwd

'C:\\Users\\Lenovo\\anaconda3\\Lib\\site-packages\\pandas'

In [101]:
import pandas as pd